### ISSUE TITLE
Xcode 10.1 can't get notification

### ISSUE THREAD

**Issue by williamhqs** [particle-iot/example-app-ios#9]
I am using Xcode 10.1 to connect, after selected photon wifi, nothing happens. No notification.

```
+(BOOL)checkSparkDeviceWifiConnection:(NSString *)networkPrefix {
NSString *SSID = info[@"SSID"];
            NSLog(@"currently connected SSID: %@",SSID);
)
```
SSID is nil.

Any help?

**Comment by RaimundasSakalauskas** [comment]
There were changes in iOS 12 / XCode 10 regarding this. Now you need to open project settings and enable "Access WIFI information" capability. 

<img width="773" alt="screen shot 2018-11-03 at 13 01 25" src="https://user-images.githubusercontent.com/3405865/47951963-a1dce000-df68-11e8-9262-deb4528ab192.png">

**Comment by meer1992** [comment]
It did not work for me. I switched "Access WIFI information" to On but the notification hasn't shown up. I even tried to switch on the background modes to On (remote notification & background fetch) but still. I'm testing on iphone5s (iOS 12.1) Xcode 10.1
